### ISSUE TITLE
The standard contract StandardTokens.sol is compiled into the empty bytecode

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1480]
On version `0.4.7-nightly.2016.12.1+commit.3a01a87a.Linux.g++`,

```
solc/solc ../std/StandardToken.sol --bin
```
yields empty bytecode.

```
$ solc/solc ../std/StandardToken.sol --bin
Warning: This is a pre-release compiler version, please do not use it in production.

======= StandardToken =======
Binary: 


======= Token =======
Binary: 

```

**Comment by chriseth** [comment]
We talked about that, this is because one of the abstract public functions only have an external implementation. The code should be fixed, though.

**Comment by pirapira** [comment]
@chriseth Even when I specify the abstract function to be `external`, I still see the empty byte code: #1486.

**Comment by axic** [comment]
Why is it defined `external` in the first place?

**Comment by pirapira** [comment]
The accessor is `external` because otherwise there is ambiguity around function types.  If we make the accessor functions available from within the contract, `x()` is ambiguous after a declaration `function () returning () public x`.  `x()` might mean calling the accessor or calling the function stored in `x`.
