### ISSUE TITLE
`return msg.sender.balance;` returns unexpected value

### ISSUE THREAD

**Issue by o0ragman0o** [ethereum/solidity#2325]
I'm raising this first as a Solidity issue but maybe a deeper issue present.

This was raised on [SE](https://ethereum.stackexchange.com/questions/16781/return-msg-sender-balance-not-acting-as-expected)  yesterday and I have confirmed unexpected behaviour with a [contract on Rinkeby](https://rinkeby.etherscan.io/address/0x40926dce51fe43c40525e4e81b7f3413e19ab981#code)

> I'm using MetaMask to connect to Rinkeby and I'm deploying the contracts via Remix. When I call the function returnsenderbalance it returns
>
> 115792089237316195423570985008687907853269984665640564039456084007913129639935
rather than my balance in Wei. The code is below:
>
```
pragma solidity ^0.4.11;

contract returnbalance{
    function returnsenderbalance() constant returns (uint){
        return msg.sender.balance;  
    }
}

```
The return value of `msg.sender.balance` appears to be a unit cast negative value unassociated with the actual account balance.

Behaviour is present in Geth.
Behaviour **not** present in the JavascriptVM which works as expected.
Have not tested on Parity.

**Comment by axic** [comment]
This is translated into this (with 0.4.12-develop.2017.5.30+commit.64f76b30.Darwin.appleclang
):
```
        /* "rb.sol":78:82  uint */
      0x0
        /* "rb.sol":100:110  msg.sender */
      caller
        /* "rb.sol":100:118  msg.sender.balance */
      0xffffffffffffffffffffffffffffffffffffffff
      and
      balance
        /* "rb.sol":93:118  return msg.sender.balance */
      swap1
      pop
        /* "rb.sol":29:127  function returnsenderbalance() constant returns (uint){... */
```

This seems to be correct. Does it work properly with on-chain transactions? It only fails with `eth_call` on geth?

**Comment by kieranelby** [comment]
FWIW, I've also seen this (and been very confused by it), in my case using MetaMask to call a constant contract function that returns the balance of an address - about 50% of the time I get the correct result, other times I get 115792089237316195423570985008687907853269984665640564039455084007913129639935. Perhaps a geth/MetaMask issue - never seen with JavascriptVM.

**Comment by axic** [comment]
@o0ragman0o @kieranelby since it is not present on ethereumjs-vm, but both of you have seen it with geth, please open an issue on go-ethereum.

**Comment by o0ragman0o** [comment]
I've realised that `msg.sender` itself does not make sense in a `constant` function. The following function returns garbage under different clients.

    contract ReturnSender {
        function retSenderAddr() public constant returns (address)
        {
            return msg.sender;
        }
    }

**Comment by axic** [comment]
From Solidity's perspective it still makes sense, it is part of the state and constant functions can read the state, just they cannot modify it.

Since this flag is also populated in the ABI JSON, certain tools (such as web3.js) will consider those functions can be executed via `eth_call`, which is true, but it still requires proper values. However, they can also be executed by other contract functions, so it doesn't make sense disallowing `msg.sender`.

I'm not sure why sender would be omitted in `eth_call` though.

**Comment by o0ragman0o** [comment]
I'm not aware enough of how `eth_call` works.  I'll raise this as a Geth issue as suggested. However, now I can't reproduce the bad behaviour returning `msg.sender` with other clients (local Remix may have been corrupted and I've been trying to stabilise all morning).

**Comment by mr-robek** [comment]
i'm experiencing the same behavior. my smartcontract looks like this:
` 
 function balanceOfEther(address user) public constant returns (uint256) {
    return user.balance;
  }
`
i deployed it to main network and every time i call it using metamask i get the same big number 11579...
caling it from etherscan "read smart contract" feature works well. 
any workarounds/solution since august?

**Comment by axic** [comment]
This is still doesn't look a Solidity bug. Please report it to Metamask or any other client you are using.

**Comment by axic** [comment]
Closing this as the generated code seemed to be correct.

**Comment by diegobes** [comment]
This is related to:

eth/api_backend.go

func (b *EthAPIBackend) GetEVM(ctx context.Context, msg core.Message, state *state.StateDB, header *types.Header, vmCfg vm.Config) (*vm.EVM, func() error, error) {
	**===> state.SetBalance(msg.From(), math.MaxBig256)**
	vmError := func() error { return nil }
	context := core.NewEVMContext(msg, header, b.eth.BlockChain(), nil)
	return vm.NewEVM(context, state, b.eth.chainConfig, vmCfg), vmError, nil
}

math.MaxBig256 == 115792089237316195423570985008687907853269984665640564039455084007913129639935

Is a constant in Geth( common/math/big.go)
