### ISSUE TITLE
UnimplementedFeatureError without any message

### ISSUE THREAD

**Issue by Remi-Burgel** [ethereum/solidity#3199]
Hi,
While trying this on one of my contract :
```
pragma solidity ^0.4.18;

contract A {
    
    struct b{
        uint c;
    }
    
    struct d {
        b e;
    }
    
    
    d public f;
}
```
I had `UnimplementedFeatureError: ` but without any message with the error and without the line where the error is, could we add something understandable for the dev because it was pretty hard to find why my contract couldn't compile.

Update : 
--------------
It also appears when you want to return a struct from a storage map/array inside an event. Example : 
```
pragma solidity ^0.4.18;

contract A {
    
    struct B{
        uint c;
    }
    
    B[] bArray;
    
    event D (B e);
    
    function f (uint g) public{
        D(bArray[g]);
    }
}
```

You can still making it work by copying the struct in memory before triggering the event : 

```
pragma solidity ^0.4.18;

contract A {
    
    struct B{
        uint c;
    }
    
    B[] bArray;
    
    event D (B e);
    
    function f (uint g) public{
        B memory h = bArray[g];
        D(h);
    }
}
```

**Comment by Remi-Burgel** [comment]
I just realised that it had nothing to do with the array so I updated the code and the title

**Comment by Remi-Burgel** [comment]
Found a new way to rise this event without any message so I bumb the post after the edit

**Comment by attente** [comment]
Hi, I'm still getting this error with solc 0.4.19 and the following files:

A.sol:

```pragma solidity ^0.4.19;
pragma experimental ABIEncoderV2;

import './B.sol';

contract A {
  function f(B.T t) external {
  }
}
```



B.sol:

```pragma solidity ^0.4.19;
pragma experimental ABIEncoderV2;

contract B {
  struct T {
    uint t;
  }
}
```

**Comment by chriseth** [comment]
Yes, this is due to the experimental nature of the feature you activated. If you change `external` to `public` it will work.

**Comment by attente** [comment]
Thanks! Is it intentional that it doesn't work with `external` functions or is it a bug?

**Comment by chriseth** [comment]
It is a not yet implemented feature.
