### ISSUE TITLE
Make usage of quotes in errors consistent

### ISSUE THREAD

**Issue by Marenz** [ethereum/solidity#7578]
Our error messages are not consistent regarding the use of quotes, e.g. some quote the function name and contract name, others don't.

We should agree on how we want to do that and make it consistent everywhere.

@erak argues for double quotes `"` around all user defined names.
I tend to agree.

**Comment by birtony** [comment]
Hey, I would be happy to improve the error messages!

**Comment by Marenz** [comment]
Glad to hear that! 

We still have to decide on how exactly this should be done, which we probably will do in tomorrows meeting. Feel free to join tomorrow (Wednesday at 15 CET, a link will be posted in gitter) in our google hangout meeting if you want to talk about it.

In any case I'll update this issue with the result of the discussion!

**Comment by birtony** [comment]
Thank you, @Marenz!

**Comment by birtony** [comment]
Hey @Marenz! Unfortunately I could not join you for the meeting today. Have you been able to reach any agreement on this issue?

**Comment by Marenz** [comment]
Yes. We'd like for all user defined names to be in quotes in all error messages. Sorry I didn't update sooner.

**Comment by birtony** [comment]
In single or in double quotes?

**Comment by Marenz** [comment]
Double quotes

**Comment by birtony** [comment]
I was looking into the error messages, and I have also noticed, that a lot of custom defined errors are used. The problem is that I am not totally sure, which exact errors should be changed. Could you, please, provide me with an example of any error that has "user defined names" within it that needs to be updated?

**Comment by Marenz** [comment]
Here are a few examples for you: :)
```
// Uses single quotes instead of double quotes
m_errorReporter.warning(_statement.location(), "Failure condition of 'send' ignored. Consider using 'transfer' instead.");
// Should be this
m_errorReporter.warning(_statement.location(), "Failure condition of \"send\" ignored. Consider using \"transfer\" instead.");
```

here no quotes at all are used:
```
m_errorReporter.typeError(
        _statement.location(),
        errorMsg +
        ". Try converting to type " +
        valueComponentType->mobileType()->toString() +
        " or use an explicit conversion."
);
// Should be this
m_errorReporter.typeError(
        _statement.location(),
        errorMsg +
        ". Try converting to type \"" +
        valueComponentType->mobileType()->toString() +
        "\" or use an explicit conversion."
);


 m_errorReporter.fatalTypeError(_tuple.location(), "Type " + inlineArrayType->toString() + " is only valid in storage.");
// Should be this
 m_errorReporter.fatalTypeError(_tuple.location(), "Type \"" + inlineArrayType->toString() + "\" is only valid in storage.");

```

**Comment by KalshuCodes** [comment]
Hey, @Marenz  Is this still left to work upon? I would be glad to contribute.

**Comment by birtony** [comment]
@kalashshah11 I am going to push an update in a bit with all the updated error messages I could've found

**Comment by axic** [comment]
Why not introduce a `toQuoted` or `toQuotedString` helper?

**Comment by leonardoalt** [comment]
@axic such as https://github.com/ethereum/solidity/issues/7733 ? ;)

**Comment by axic** [comment]
Can't we just implement our alternative in 3 lines of code?

**Comment by leonardoalt** [comment]
Sure, that'd work

**Comment by Marenz** [comment]
When @erak and I talked about it we decided to make it all consistent as a first step and as a second step use a function like that.

**Comment by axic** [comment]
Sounds like a lot of extra work :wink:

**Comment by Marenz** [comment]
I argued along similar lines and I forgot eraks counter-argument ;)

**Comment by erak** [comment]
Well, I think I had no strong opinion on the process ;-) Would agree with @axic here and start using the helper function right away.

**Comment by Marenz** [comment]
What does that mean in regards to the pending PR?

**Comment by antara-gandhi** [comment]
Hello! I'm new to contributing to open-source, and I saw this issue was still open. It looks like it should be resolved to me - is there still something that needs to be done that I could help out with?

**Comment by cameel** [comment]
@antara-gandhi We still do not have the helper and quoting in error messages is not used consistently :) Well, we do have [`escapeAndQuoteString()`](https://github.com/ethereum/solidity/blob/v0.8.7/libsolutil/CommonData.h#L555-L557) and I've seen it used for quoting sometimes but I'm not sure we really want escaping there and the name is a bit long for something to be used as often as quoting.

So my suggestion would be to start by creating the helper in `CommonData.h`, then find some messages and use it in them.

**Comment by chriseth** [comment]
I'm not sure the helper is that helpful (haha), we certainly do not want to escape in these cases.

**Comment by cameel** [comment]
Well, it's an old issue so maybe the sentiment changed here :)


Personally, I'd prefer something like
```c++
m_errorReporter.typeError(
        _statement.location(),
        errorMsg +
        ". Try converting to type " +
        quoted(valueComponentType->mobileType()->toString()) +
        " or use an explicit conversion."
);
```
over
```c++
m_errorReporter.typeError(
        _statement.location(),
        errorMsg +
        ". Try converting to type \"" +
        valueComponentType->mobileType()->toString() +
        "\" or use an explicit conversion."
);
```

or we could switch to fmtlib: https://github.com/ethereum/solidity/pull/11273#discussion_r620268452 :)

**Comment by chriseth** [comment]
I think the second version makes it much clearer what is between the strings. For the one with `quoted` you first have to read `quoted` and discard it as non-essential.

**Comment by cameel** [comment]
But with escaped quotes you have to parse them visually and discard as non-essential :) When I see that when skimming over the code I just skip it as something complex not worth analyzing closer while in the version with `quoted()` I can easily see that it's just an expression between two strings.

Anyway, I do not feel very strongly about this issue and I'm fine with either, just want to have a decision here so that contributors can work on it. Looks like no one was against quoting itself and it's just a matter of how we insert them (with or without a helper) so to cut the discussion short, I think it would be fine to start working on this by just inserting quotes directly. We can add a helper later if we get some consensus here.
