### ISSUE TITLE
Solc fails to install on Linux - tries to replace libevmasm.so installed with libethereum

### ISSUE THREAD

**Issue by Hibryda** [ethereum/solidity#851]
Nothing of much importance actually - but Solc refuses to install 
`DistroRelease: elementary OS 0.3.2
DuplicateSignature: package:solc:1.2.9-SNAPSHOT--20160630-f09ff00~trusty-0ubuntu1 [origin: unknown]:trying to overwrite '/usr/lib/libevmasm.so', which is also in package libethereum:amd64 1.2.9-SNAPSHOT--20160630-f09ff00~trusty-0ubuntu1
ProcVersionSignature: Ubuntu 3.19.0-66.74~14.04.1-generic 3.19.8-ckt22
Uname: Linux 3.19.0-66-generic x86_64`

**Comment by bobsummerwill** [comment]
Hey, @Hibryda,

Yes, Christian is in the process of switching our PPAs over, with cpp-ethereum and solidity being split apart.

What you can do in the short-term is uninstall cpp-ethereum and then the solidity install should work.

We will get the "shapes" right in the very near future!   Best wishes.

**Comment by primehat23** [comment]
This is the issue I have too.

**Comment by primehat23** [comment]
goldhat00@goldhat00-desktop:~$ sudo apt-get remove cpp-ethereum
Reading package lists... Done
Building dependency tree  
Reading state information... Done
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 solc : Depends: libethereum (= 1.2.9-SNAPSHOT--20160628-6a05dd7~trusty-0ubuntu1) but 1.2.9-SNAPSHOT--20160630-f09ff00~trusty-0ubuntu1 is to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).

**Comment by chriseth** [comment]
It should be fixed now, can you test, please (apt-get update && apt-get upgrade)?

**Comment by Hibryda** [comment]
@chriseth Unfortunately still an issue:
`Preparing to unpack .../solc_1%3a0.3.6-nightly-2016-08-10-fh-3fc68da-0ubuntu1~trusty_amd64.deb ...
Unpacking solc:amd64 (1:0.3.6-nightly-2016-08-10-fh-3fc68da-0ubuntu1~trusty) over (1.2.9-SNAPSHOT--20160630-f09ff00~trusty-0ubuntu1) ...
dpkg: error processing archive /var/cache/apt/archives/solc_1%3a0.3.6-nightly-2016-08-10-fh-3fc68da-0ubuntu1~trusty_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/libsolidity.so', which is also in package libethereum:amd64 1.2.9-SNAPSHOT--20160630-f09ff00~trusty-0ubuntu1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
E: Sub-process /usr/bin/dpkg returned an error code (1)
`
@bobsummerwill Yes, ultimately will purge cpp-eth. Just informed about the issue.

**Comment by bobsummerwill** [comment]
You will need to uninstall cpp-ethereum first.   Please could you try that, @Hibryda?

We'll get them all the right shape soon.    Just clashy during the transition, which is proving very painful.

**Comment by Hibryda** [comment]
@bobsummerwill I uninstalled cpp-ethereum, but this wasn't the total resolution. I also had to get rid of libethereum because it locked installation of solc. But without libethereum there was no candidate for update - an effect of split of these entities. So had to manually force solc to install from deb package at the end.
So the path was as follows:
sudo apt-get remove --purge cpp-ethereum
sudo apt-get remove --purge libethereum
sudo apt-get update && sudo apt-get upgrade #(no candidates)
sudo dpkg -i /path/to/solc_pack
sudo apt-get install -f
I did it this way (with success) and actually cannot see easier way, as these the libethereum and solc interlock. This should be fixed somehow.

**Comment by Hibryda** [comment]
Ah, and I could actually make it easier of course, just force installing without dependencies, but wanted a cleaner version to be sure. Now it works fine.

**Comment by chriseth** [comment]
Thanks for the detailed report! We will improve the experience once we have new cpp-ethereum ppa packages.

**Comment by simpletechnology** [comment]
ntu1_amd64.deb ...
Unpacking libethereum:amd64 (1.2.9-SNAPSHOT--20160629-6a05dd7~xenial-0ubuntu1) ...
dpkg: error processing archive /var/cache/apt/archives/libethereum_1.2.9-SNAPSHOT--20160629-6a05dd7~xenial-0ubuntu1_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/libsolidity.so', which is also in package solc:amd64 1:0.3.6-nightly-2016-08-10-fh-3fc68da-0ubuntu1~xenial
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Processing triggers for libc-bin (2.23-0ubuntu3) ...
Errors were encountered while processing:
 /var/cache/apt/archives/libethereum_1.2.9-SNAPSHOT--20160629-6a05dd7~xenial-0ubuntu1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
ubuntu@ip-172-31-11-219:~$

**Comment by simpletechnology** [comment]
solc and libethereum cannot be installed together on ubuntu trusty.

**Comment by simpletechnology** [comment]
The following NEW packages will be installed:
  libethereum
0 upgraded, 1 newly installed, 0 to remove and 27 not upgraded.
10 not fully installed or removed.
Need to get 0 B/2,890 kB of archives.
After this operation, 14.6 MB of additional disk space will be used.
Do you want to continue? [Y/n](Reading database ... 66657 files and directories currently installed.)
Preparing to unpack .../libethereum_1.2.9-SNAPSHOT--20160628-6a05dd7~trusty-0ubuntu1_amd64.deb ...
Unpacking libethereum:amd64 (1.2.9-SNAPSHOT--20160628-6a05dd7~trusty-0ubuntu1) ...
dpkg: error processing archive /var/cache/apt/archives/libethereum_1.2.9-SNAPSHOT--20160628-6a05dd7~trusty-0ubuntu1_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/libsolidity.so', which is also in package solc:amd64 1:0.3.6-0ubuntu1~trusty
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/libethereum_1.2.9-SNAPSHOT--20160628-6a05dd7~trusty-0ubuntu1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by simpletechnology** [comment]
the main problem is this;

trying to overwrite '/usr/lib/libsolidity.so', which is also in package solc:amd64 1:0.3.6-0ubuntu1~trusty

/usr/lib/libsolidity.so is contained inside two packages that both need to be installed together. it's impossible to do so otherwise, as apt-get checks this....

**Comment by chriseth** [comment]
I'm sorry, yes, until we have new ppa packages for cpp-ethereum they cannot be both installed at the same time.

**Comment by Hibryda** [comment]
It can temporarily done by repacking one of packages: ar, edit control archive, pack again. Dirty, but should do the job.

**Comment by connorchang** [comment]
I am still having the same issue, and my whole apt system broke, is there any way to fix this? I tried to the commands above, didn't work.
